version: '3.8'

services:
  laravel:
    image: nombreDeTuImagenLaravel
    ports:
      - "8100:8100"
    volumes:
      - ./ruta/a/tu/proyecto:/ruta/en/el/contenedor
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
    command: "composer install && php artisan serve --host=0.0.0.0 --port=8100"
    networks:
      - coolify_net

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=contraseñaRoot
      - MYSQL_DATABASE=nombreDeTuBaseDeDatos
    networks:
      - coolify_net

  nodejs:
    image: node:18
    ports:
      - "3200:3200"
    volumes:
      - ./ruta/a/tu/proyecto:/ruta/en/el/contenedor
    command: "npm install && node server.js"
    depends_on:
      - mariadb
    networks:
      - coolify_net

networks:
  coolify_net:
    driver: bridge
