version: '3.8'

services:
  laravel:
    image: php:8.2-apache
    ports:
      - "8100:8100"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
    command: sh -c "apt-get update && apt-get install -y git && php -r 'copy(\"https://getcomposer.org/installer\", \"composer-setup.php\");' && php composer-setup.php --install-dir=/usr/local/bin --filename=composer && rm composer-setup.php && composer install && php artisan serve --host=0.0.0.0 --port=8100"
    networks:
      - coolify_net

  mariadb:
     image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: tinyq
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
    networks:
      - coolify_net

  nodejs:
    image: node:18
    ports:
      - "3200:3200"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && node server.js"
    depends_on:
      - mariadb
    networks:
      - coolify_net

networks:
  coolify_net:
    driver: bridge

    
