version: '3.8'

services:
  laravel:
    image: php:8.2-apache
    ports:
      - "8100:8100"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
    command: sh -c "apt-get update && apt-get install -y git && curl -sS https://getcomposer.org/installer | php && php composer.phar install && php artisan serve --host=0.0.0.0 --port=8100"
    networks:
      - coolify_net

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_DATABASE=tinyq
    networks:
      - coolify_net

  nodejs:
    image: node:18
    ports:
      - "3200:3200"
    working_dir: /usr/src/app
    command: sh -c "npm install && node server.js"
    depends_on:
      - mariadb
    networks:
      - coolify_net

networks:
  coolify_net:
    driver: bridge
