version: '3.1'

services:

    laravel:
        image: webdevops/php-apache-dev:8.2
        ports:
          - "8000:8000"
        volumes:
          - ".:/var/www"
        environment:
          - WEB_DOCUMENT_ROOT=/app/public
        depends_on:
          - mariadb
          - nodejs
        command: /bin/bash -c "cd /var/www && ls && composer install && php artisan serve --host=0.0.0.0 --port=8000"
        networks:
          - laravel-network

    mariadb:
        image: mysql
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: tinyq
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
        networks:
            - laravel-network

    nodejs:
        image: node:18
        ports:
            - "3200:3200"
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: /bin/bash -c "if [ ! -d node_modules ]; then npm install; fi && node server.js"
        networks:
            - laravel-network


networks:
    laravel-network:
        driver: bridge
