version: '3.1'

services:
    mariadb:
        image: mysql
        command: --default-authentication-plugin=caching_sha2_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: tinyq
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8082:80"
        environment:
            - PMA_ARBITRARY=1


