version: '3.8'

services:
  laravel:
    image: php:8.2-apache
    ports:
      - "8100:8100"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
    networks:
      - coolify_net

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
            MYSQL_DATABASE: tinyq
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
    networks:
      - coolify_net

  nodejs:
    image: node:18
    ports:
      - "3200:3200"
    volumes:
      - .:/usr/src/app
    command: "node server.js"
    depends_on:
      - mariadb
    networks:
      - coolify_net

networks:
  coolify_net:
    driver: bridge

